// ISO 3166-1 alpha-2 country list grouped by region for the
// /admin/geo-block picker. Trimmed to the codes Vercel actually
// emits in `x-vercel-ip-country` (live + dependent territories that
// resolve to a real population). Display names are English so the
// admin UI matches the codes you'd paste from a compliance memo.

export type Country = { code: string; name: string };
export type Region = { name: string; countries: Country[] };

export const REGIONS: Region[] = [
  {
    name: "Americas",
    countries: [
      { code: "US", name: "United States" },
      { code: "CA", name: "Canada" },
      { code: "MX", name: "Mexico" },
      { code: "BR", name: "Brazil" },
      { code: "AR", name: "Argentina" },
      { code: "CL", name: "Chile" },
      { code: "CO", name: "Colombia" },
      { code: "PE", name: "Peru" },
      { code: "VE", name: "Venezuela" },
      { code: "UY", name: "Uruguay" },
      { code: "PY", name: "Paraguay" },
      { code: "BO", name: "Bolivia" },
      { code: "EC", name: "Ecuador" },
      { code: "CR", name: "Costa Rica" },
      { code: "PA", name: "Panama" },
      { code: "DO", name: "Dominican Republic" },
      { code: "GT", name: "Guatemala" },
      { code: "HN", name: "Honduras" },
      { code: "SV", name: "El Salvador" },
      { code: "NI", name: "Nicaragua" },
      { code: "CU", name: "Cuba" },
      { code: "JM", name: "Jamaica" },
      { code: "TT", name: "Trinidad and Tobago" },
      { code: "PR", name: "Puerto Rico" },
    ],
  },
  {
    name: "Europe",
    countries: [
      { code: "GB", name: "United Kingdom" },
      { code: "IE", name: "Ireland" },
      { code: "FR", name: "France" },
      { code: "DE", name: "Germany" },
      { code: "ES", name: "Spain" },
      { code: "PT", name: "Portugal" },
      { code: "IT", name: "Italy" },
      { code: "NL", name: "Netherlands" },
      { code: "BE", name: "Belgium" },
      { code: "LU", name: "Luxembourg" },
      { code: "CH", name: "Switzerland" },
      { code: "AT", name: "Austria" },
      { code: "DK", name: "Denmark" },
      { code: "SE", name: "Sweden" },
      { code: "NO", name: "Norway" },
      { code: "FI", name: "Finland" },
      { code: "IS", name: "Iceland" },
      { code: "PL", name: "Poland" },
      { code: "CZ", name: "Czechia" },
      { code: "SK", name: "Slovakia" },
      { code: "HU", name: "Hungary" },
      { code: "RO", name: "Romania" },
      { code: "BG", name: "Bulgaria" },
      { code: "GR", name: "Greece" },
      { code: "RS", name: "Serbia" },
      { code: "HR", name: "Croatia" },
      { code: "SI", name: "Slovenia" },
      { code: "BA", name: "Bosnia and Herzegovina" },
      { code: "ME", name: "Montenegro" },
      { code: "MK", name: "North Macedonia" },
      { code: "AL", name: "Albania" },
      { code: "EE", name: "Estonia" },
      { code: "LV", name: "Latvia" },
      { code: "LT", name: "Lithuania" },
      { code: "UA", name: "Ukraine" },
      { code: "BY", name: "Belarus" },
      { code: "RU", name: "Russia" },
      { code: "MD", name: "Moldova" },
      { code: "MT", name: "Malta" },
      { code: "CY", name: "Cyprus" },
    ],
  },
  {
    name: "Asia & Pacific",
    countries: [
      { code: "CN", name: "China" },
      { code: "HK", name: "Hong Kong" },
      { code: "TW", name: "Taiwan" },
      { code: "JP", name: "Japan" },
      { code: "KR", name: "South Korea" },
      { code: "KP", name: "North Korea" },
      { code: "MN", name: "Mongolia" },
      { code: "VN", name: "Vietnam" },
      { code: "TH", name: "Thailand" },
      { code: "MY", name: "Malaysia" },
      { code: "SG", name: "Singapore" },
      { code: "ID", name: "Indonesia" },
      { code: "PH", name: "Philippines" },
      { code: "IN", name: "India" },
      { code: "PK", name: "Pakistan" },
      { code: "BD", name: "Bangladesh" },
      { code: "LK", name: "Sri Lanka" },
      { code: "NP", name: "Nepal" },
      { code: "AF", name: "Afghanistan" },
      { code: "KZ", name: "Kazakhstan" },
      { code: "UZ", name: "Uzbekistan" },
      { code: "KG", name: "Kyrgyzstan" },
      { code: "TJ", name: "Tajikistan" },
      { code: "TM", name: "Turkmenistan" },
      { code: "AZ", name: "Azerbaijan" },
      { code: "GE", name: "Georgia" },
      { code: "AM", name: "Armenia" },
      { code: "AU", name: "Australia" },
      { code: "NZ", name: "New Zealand" },
    ],
  },
  {
    name: "Middle East",
    countries: [
      { code: "AE", name: "United Arab Emirates" },
      { code: "SA", name: "Saudi Arabia" },
      { code: "QA", name: "Qatar" },
      { code: "KW", name: "Kuwait" },
      { code: "BH", name: "Bahrain" },
      { code: "OM", name: "Oman" },
      { code: "TR", name: "Turkey" },
      { code: "IL", name: "Israel" },
      { code: "JO", name: "Jordan" },
      { code: "LB", name: "Lebanon" },
      { code: "SY", name: "Syria" },
      { code: "IQ", name: "Iraq" },
      { code: "IR", name: "Iran" },
      { code: "YE", name: "Yemen" },
    ],
  },
  {
    name: "Africa",
    countries: [
      { code: "EG", name: "Egypt" },
      { code: "MA", name: "Morocco" },
      { code: "TN", name: "Tunisia" },
      { code: "DZ", name: "Algeria" },
      { code: "LY", name: "Libya" },
      { code: "SD", name: "Sudan" },
      { code: "ZA", name: "South Africa" },
      { code: "NG", name: "Nigeria" },
      { code: "KE", name: "Kenya" },
      { code: "ET", name: "Ethiopia" },
      { code: "GH", name: "Ghana" },
      { code: "SN", name: "Senegal" },
      { code: "CI", name: "Côte d'Ivoire" },
      { code: "TZ", name: "Tanzania" },
      { code: "UG", name: "Uganda" },
      { code: "ZW", name: "Zimbabwe" },
      { code: "ZM", name: "Zambia" },
      { code: "AO", name: "Angola" },
      { code: "MZ", name: "Mozambique" },
      { code: "RW", name: "Rwanda" },
      { code: "CM", name: "Cameroon" },
    ],
  },
];

export function findCountry(code: string): Country | null {
  const upper = code.toUpperCase();
  for (const r of REGIONS) {
    const hit = r.countries.find((c) => c.code === upper);
    if (hit) return hit;
  }
  return null;
}
